export const commentsByPostId = {
  1: [
    {
      id: 1001,
      writer: "제로나라",
      time: "2시간 전",
      content: "저는 AI작업은 바로 적용하지 않고 항상 확인합니다.\n1. 불필요한 코드 반복이 없는지 확인\n2. 내가 생각하지 못한 방향을 제시 했다면 다시 공부가 됩니다.\n맹신하지 않으면 뭐든 도움이 됩니다.^^",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 1002,
      writer: "글리터",
      time: "3시간 전",
      content: "임의 코드를 적절하게 다듬어 적용하는 안목이 경쟁력일 겁니다",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  2: [
    {
      id: 2001,
      writer: "직딩",
      time: "2시간 전",
      content: "현업에 있으면서 요즘 가장 피부로 느끼는 지점입니다.\n툴을 다루는 기술은 평준화되고 있어서,\n이제는 AI로 빨리 만든 결과물로 어떻게 비즈니스 임팩트를 낼 것인가를 고민하는 사람만 살아남겠더라고요.",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 2002,
      writer: "심플스",
      time: "3시간 전",
      content: "지금 말씀 하신걸 몰라서 개발자들이 힘들다 할까요?^^",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 2003,
      writer: "옵션",
      time: "4시간 전",
      content: "저는 무엇을 만들 수 있느냐가 중요하다고봅니다 어차피 개발자가 체질상 물건못팔아요",
      emoji: "🤓",
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
    {
      id: 2004,
      writer: "익명",
      time: "5시간 전",
      content: "가치가 없어져버린 뒤쳐져버린것들은 고려사항도아니죠 기존에없던 새로나온 아이템들 만들어팔면되요",
      emoji: "😊",
      reactions: { like: 0, laugh: 0, agree: 0, thanks: 1, wow: 0 },
    },
  ],
  3: [
    {
      id: 3001,
      writer: "지운아빠",
      time: "2시간 전",
      content: "그때그떄 달라요",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 3002,
      writer: "헤더캣",
      time: "3시간 전",
      content: "유저수 만명 내외의 서비스에선 프론트엔드가 어렵고\n그보다 규모가 커지면 백엔드가 점점 어려워지고…",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  4: [
    {
      id: 4001,
      writer: "솔나방",
      time: "2시간 전",
      content: "그러게요,,",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  5: [
    {
      id: 5001,
      writer: "Gothrock",
      time: "2시간 전",
      content: "느긋하게 지운이 손 잡고 PC방 가세요",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 5002,
      writer: "지운아빠",
      time: "3시간 전",
      content: "다행히 핫스팟 켜서 버티고 있습니다. ㅎㅎㅎ\n오랜만에 TV 안 켜고 도란도란 얘기만 하면서 저녁 먹었더니 나름 운치가 있네요. ㅎㅎㅎ",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 5003,
      writer: "Gothrock",
      time: "4시간 전",
      content: "좋은 시절이신겁니다. 애들 시집장가 다 가고나니 그때가 저는 그리워요.",
      emoji: "🤓",
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  6: [
    {
      id: 6001,
      writer: "행인",
      time: "2시간 전",
      content: "개발자라고 봄 코드를 볼 줄 아니까",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 6002,
      writer: "박지성",
      time: "3시간 전",
      content: "아직은 좀 더 두고봐야하지 않을까요?",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  7: [
    {
      id: 7001,
      writer: "미니님",
      time: "2시간 전",
      content: "도배를 안하시는 습관이 중요할 것 같습니다.",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 7002,
      writer: "지운아빠",
      time: "3시간 전",
      content: "매너를 쌓는 곳이 아니라\n쌓아온 매너를 보여주시는 곳이 되길 바랍니다.",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  8: [
    {
      id: 8001,
      writer: "컴대장",
      time: "2시간 전",
      content: "공감합니다. 한개 돌렸더니 5분도 안되서 쉬라고 하네요.ㅎㅎ",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 8002,
      writer: "시인",
      time: "3시간 전",
      content: "많이 괜찮은가보네요.",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 8003,
      writer: "실전코딩",
      time: "4시간 전",
      content: "저도 돌려보니 확실히 퀄러티가 남다르더라구요\n그래서 고민인게 메인은 Fable로 돌리고 서브 에이전트들은 구독형으로 할까?\n심각하게 고민중입니다 ㅎㅎ",
      emoji: "🤓",
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  9: [
    {
      id: 9001,
      writer: "울라프",
      time: "2시간 전",
      content: "홍명보에게만 화살이 쏟아지기보다는,,",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  10: [
    {
      id: 10001,
      writer: "웨이브웹",
      time: "2시간 전",
      content: "다 자기 말이 맞다고 생각하기 때문이 아닐까요?",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 10002,
      writer: "조각조각",
      time: "3시간 전",
      content: "자원봉사를 그 바쁜 와중에도 하신다는 것 자체만으로 이미 대단하십니다. 생각도 없거나 있어도 생각처럼 쉽지 않죠.\n노인이 되면 대체로, 저도 점점 그렇게 변해 가는 것 같습니다만, 변화를 추구할 에너지가 고갈되는 것 같습니다.",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  11: [
    {
      id: 11001,
      writer: "뉴스",
      time: "2시간 전",
      content: "최근 뉴스 보니까 다크모드가 더 눈에 안좋다고 하더라고요",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  12: [
    {
      id: 12001,
      writer: "테스터 1",
      time: "2시간 전",
      content: "저도 파이썬이 가장 쉬웠어요",
      emoji: "😎",
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 12002,
      writer: "테스터 2",
      time: "3시간 전",
      content: "저는 파이썬이 가장 어려웠어요",
      emoji: "🙂",
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 12003,
      writer: "테스터 3",
      time: "4시간 전",
      content: "재밌네요",
      emoji: "🤓",
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  201: [
    {
      id: 201001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '반갑습니다~',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  202: [
    {
      id: 202001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '앞으로 잘해봐요~',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  203: [
    {
      id: 203001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '화이팅입니다~',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
}
