export const commentsByPostId = {
  1: [
    {
      id: 1001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 1002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 1003,
      writer: '리액트학생',
      time: '3시간 전',
      content: 'state를 어디에 둘지 이해하는 데 도움이 됐어요.',
      emoji: '🤓',
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  2: [
    {
      id: 2001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  3: [
    {
      id: 3001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 3002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  4: [
    {
      id: 4001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 4002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  5: [
    {
      id: 5001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 5002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 5003,
      writer: '리액트학생',
      time: '3시간 전',
      content: 'state를 어디에 둘지 이해하는 데 도움이 됐어요.',
      emoji: '🤓',
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  6: [
    {
      id: 6001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 6002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  7: [
    {
      id: 7001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  8: [
    {
      id: 8001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 8002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 8003,
      writer: '리액트학생',
      time: '3시간 전',
      content: 'state를 어디에 둘지 이해하는 데 도움이 됐어요.',
      emoji: '🤓',
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  9: [
    {
      id: 9001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 9002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 9003,
      writer: '리액트학생',
      time: '3시간 전',
      content: 'state를 어디에 둘지 이해하는 데 도움이 됐어요.',
      emoji: '🤓',
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  10: [
    {
      id: 10001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 10002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 10003,
      writer: '리액트학생',
      time: '3시간 전',
      content: 'state를 어디에 둘지 이해하는 데 도움이 됐어요.',
      emoji: '🤓',
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  101: [
    {
      id: 101001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 101002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  102: [
    {
      id: 102001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  104: [
    {
      id: 104001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 104002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 104003,
      writer: '리액트학생',
      time: '3시간 전',
      content: 'state를 어디에 둘지 이해하는 데 도움이 됐어요.',
      emoji: '🤓',
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
  201: [
    {
      id: 201001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 201002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  202: [
    {
      id: 202001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
  ],
  203: [
    {
      id: 203001,
      writer: '실전코딩',
      time: '5시간 전',
      content: '컴포넌트로 나누니까 구조가 훨씬 보기 좋아졌네요.',
      emoji: '😎',
      reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 203002,
      writer: 'Glitter Gim',
      time: '4시간 전',
      content: '검색하고 페이지 이동되는 흐름이 잘 보입니다.',
      emoji: '🙂',
      reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    },
    {
      id: 203003,
      writer: '리액트학생',
      time: '3시간 전',
      content: 'state를 어디에 둘지 이해하는 데 도움이 됐어요.',
      emoji: '🤓',
      reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    },
  ],
}
