const today = new Date().toLocaleDateString('ko-KR', {
  month: '2-digit',
  day: '2-digit',
})

export const freePosts = [
  {
    id: 1,
    boardType: 'free',
    category: '자유',
    title: 'React Router로 SPA 게시판 만들기',
    writer: '홍길동',
    date: today,
    views: 52,
    comments: 3,
    isNew: true,
    reactions: { like: 1, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    content: 'React Router를 사용해서 자유게시판, 자료게시판, 가입인사 페이지를 나누어 보았습니다.',
  },
  {
    id: 2,
    boardType: 'free',
    category: '자유',
    title: '다크모드 토글 구현 예제 공유합니다',
    writer: '김코딩',
    date: today,
    views: 63,
    comments: 1,
    isNew: true,
    reactions: { like: 0, laugh: 2, agree: 0, thanks: 0, wow: 0 },
    content: 'useState로 다크모드 상태를 관리하는 예제를 정리했습니다.',
  },
  {
    id: 3,
    boardType: 'free',
    category: '자유',
    title: '프론트엔드와 백엔드 중 어떤게 더 어렵나요?',
    writer: '이리액트',
    date: today,
    views: 41,
    comments: 2,
    isNew: true,
    reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    content: '프론트엔드와 백엔드 중 어떤 부분이 더 어렵게 느껴지는지 궁금합니다.',
    poll: {
      title: '프론트엔드와 백엔드 중 어떤게 더 어렵나요?',
      type: 'single',
      deadline: '24시간',
      voters: 0,
      isVoted: false,
      selectedOptionIds: [],
      options: [
        { id: 'option-1', text: '프론트엔드', count: 0 },
        { id: 'option-2', text: '백엔드', count: 0 },
      ],
    },
  },
  {
    id: 4,
    boardType: 'free',
    category: '자유',
    title: 'Pagination 구현 방식 비교하기',
    writer: '박자바',
    date: today,
    views: 39,
    comments: 2,
    isNew: true,
    reactions: { like: 2, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    content: '한 페이지에 8개씩 글을 보여주는 페이지네이션 방식을 비교해보았습니다.',
  },
  {
    id: 5,
    boardType: 'free',
    category: '자유',
    title: 'useState 사용법 질문입니다.',
    writer: '최프론트',
    date: today,
    views: 18,
    comments: 4,
    isNew: true,
    reactions: { like: 0, laugh: 0, agree: 0, thanks: 2, wow: 0 },
    content: 'useState로 입력값을 관리할 때 헷갈리는 부분이 있어 질문합니다.',
  },
  {
    id: 6,
    boardType: 'free',
    category: '자유',
    title: 'AI 시대 최고 수혜자는 누구일까요?',
    writer: '정리왕',
    date: today,
    views: 77,
    comments: 2,
    isNew: false,
    reactions: { like: 1, laugh: 0, agree: 2, thanks: 0, wow: 0 },
    content: '수업 시간에 이야기했던 AI 시대 직무 변화에 대해 투표를 만들어봤습니다.',
    poll: {
      title: 'AI 시대 최고 수혜자는?',
      type: 'single',
      deadline: '24시간',
      voters: 12,
      isVoted: true,
      selectedOptionIds: ['option-1'],
      options: [
        { id: 'option-1', text: '개발자', count: 5 },
        { id: 'option-2', text: 'PM', count: 2 },
        { id: 'option-3', text: '웹디자이너', count: 3 },
        { id: 'option-4', text: '마케터', count: 2 },
      ],
    },
  },
  {
    id: 7,
    boardType: 'free',
    category: '자유',
    title: 'CSS 파일을 컴포넌트별로 나누는 방법',
    writer: '스타일러',
    date: today,
    views: 44,
    comments: 1,
    isNew: false,
    reactions: { like: 0, laugh: 0, agree: 1, thanks: 1, wow: 0 },
    content: 'CSS 파일을 기능별로 나누면 유지보수가 훨씬 쉬워지는 것 같습니다.',
  },
  {
    id: 8,
    boardType: 'free',
    category: '자유',
    title: 'props로 데이터를 넘기는 이유가 궁금합니다',
    writer: '리액트초보',
    date: today,
    views: 21,
    comments: 5,
    isNew: false,
    reactions: { like: 0, laugh: 1, agree: 0, thanks: 0, wow: 0 },
    content: '부모 컴포넌트에서 자식 컴포넌트로 데이터를 넘기는 흐름이 아직 조금 헷갈립니다.',
  },
  {
    id: 9,
    boardType: 'free',
    category: '자유',
    title: '게시판 프로젝트 제출 전 체크리스트',
    writer: '관리자',
    date: today,
    views: 88,
    comments: 6,
    isNew: false,
    reactions: { like: 3, laugh: 0, agree: 1, thanks: 1, wow: 0 },
    content: '제출 전 라우터, 컴포넌트 분리, 반응형, 상태 관리가 잘 되는지 확인해보세요.',
  },
  {
    id: 10,
    boardType: 'free',
    category: '자유',
    title: 'AI 웹앱 디자인 아이디어 모음',
    writer: '디자인러',
    date: today,
    views: 74,
    comments: 3,
    isNew: false,
    reactions: { like: 0, laugh: 0, agree: 0, thanks: 0, wow: 2 },
    content: 'AI를 활용한 웹앱 디자인 아이디어를 정리해서 공유합니다.',
  },
]