export const freePosts = [
  {
      id: 1,
      boardType: "free",
      category: "자유",
      title: "코딩이 상향 표준화되니까 …",
      writer: "인더월드",
      date: "07.06.",
      views: 26,
      isNew: true,
      reactions: {
        like: 1,
        laugh: 0,
        agree: 0,
        thanks: 0,
        wow: 0,
      },
      content: "예전엔 좋은 개발 소스 하나 구하면 보물처럼 귀하게 보고 분석했는데,\n요즘은 AI가 뚝딱 짜주니까 코드를 너무 가볍게 생각하게 되는 것 같음..\n기술은 발전했는데, 코드 한 줄 대하는 태도나 예전 같은 집요함이 사라진 것 같아 조금은 씁쓸함    :))",
      files: [
        {
          name: "coding-standard.png",
          src: "/post-images/coding-standard.png",
          type: "image",
        },
      ],
    },
  {
      id: 2,
      boardType: "free",
      category: "자유",
      title: "그래서 어떻게 돈을 벌건가요?",
      writer: "리자",
      date: "07.06.",
      views: 32,
      isNew: true,
      reactions: {
        like: 0,
        laugh: 2,
        agree: 0,
        thanks: 0,
        wow: 0,
      },
      content: "예전에는 개발이 어려웠기 때문에 개발 능력이 경쟁력이었습니다\n하지만 AI가 점점 발전하면 개발은 점점 쉬워질 가능성이 높습니다\n\n그렇다면 다음 질문은 자연스럽게 이렇게 이어질겁니다\n\"그래서 AI로 어떻게 돈을 벌건가요?\n\n\n그런데 이 질문에 대한 답은 의외로 잘 나오지 않습니다\nAI로 홈페이지를 만들 수 있다\nAI로 쇼핑몰도 만들 수 있다\nAI로 앱도 만들 수 있다\n그런데 홈페이지를 만드는 것과 홈페이지로 돈을 버는 것은 전혀 다른 문제입니다\n오히려 앞으로는 개발보다 운영, 마케팅, 영업, 고객관리 같은 영역의 중요성이 더 커질 수 있습니다\n\n누군가는 AI로 일감이 줄었다고 말하고, \n반대로 누군가는 아직도 견적 문의가 넘쳐난다고 말합니다\n\n누군가는 개발자의 미래를 걱정하고, \n또 누군가는 AI가 해주는 일과 사람이 해야 할 일은 다르다고 말합니다\n\n누가 맞는지는 아직 아무도 모릅니다\n다만 한 가지는 분명합니다\nAI 시대에도 통장에 돈이 들어오는 사람은 살아남고, 그렇지 못한 사람은 어려워진다는 것입니다\n\n결국 중요한 것은\n\"AI가 무엇을 만들어 줄 수 있는가?\"\n\n가 아니라 \n\"AI를 이용해서 어떤 가치를 만들고, 어떻게 돈을 벌것인가?\"\n\n입니다\n\n기술은 점점 평준화 되고 있습니다\n이제는 무엇을 만들 수 있느냐보다, 무엇을 팔 수 있느냐가 더 중요한 시대가 되었습니다",
      files: [
        {
          name: "money-question.png",
          src: "/post-images/money-question.png",
          type: "image",
        },
      ],
    },
  {
      id: 3,
      boardType: "free",
      category: "자유",
      title: "프론트 엔드와 백엔드 중 어떤게 더 어렵나요?",
      writer: "익명",
      date: "07.06.",
      views: 38,
      isNew: true,
      reactions: {
        like: 0,
        laugh: 0,
        agree: 1,
        thanks: 0,
        wow: 0,
      },
      content: "프론트 엔드와 백엔드 중 어떤 부분이 더 어렵게 느껴지는지 궁금합니다.",
      poll: {
        title: "프론트 엔드와 백엔드 중 어떤게 더 어렵나요?",
        type: "single",
        deadline: "24시간",
        voters: 0,
        isVoted: false,
        selectedOptionIds: [],
        options: [
          {
            id: "option-1",
            text: "프론트엔드",
            count: 0,
          },
          {
            id: "option-2",
            text: "백엔드",
            count: 0,
          },
        ],
      },
    },
  {
      id: 4,
      boardType: "free",
      category: "자유",
      title: "울적하네요.",
      writer: "솔나방",
      date: "07.06.",
      views: 29,
      isNew: true,
      reactions: {
        like: 2,
        laugh: 0,
        agree: 1,
        thanks: 0,
        wow: 0,
      },
      content: "오늘이면  Fable5 사용 끝이네요. \n내일부터 Fable5 금단 증상 때문에 당분간 힘들거 같음. \n\n\nps. 7.7일에 GPT-5.6 나온다는 얘기가 있네요.",
      files: [
        {
          name: "blue-mood.png",
          src: "/post-images/blue-mood.png",
          type: "image",
        },
      ],
    },
  {
      id: 5,
      boardType: "free",
      category: "자유",
      title: "AI 데이터센터가 문제가 아니네요.",
      writer: "지운아빠",
      date: "07.06.",
      views: 24,
      isNew: true,
      reactions: {
        like: 0,
        laugh: 0,
        agree: 0,
        thanks: 2,
        wow: 0,
      },
      content: "인터넷 회선 문제 생겨서 이 방법 저 방법 다해봤는데 안 돼서 고객센터 전화해 봤더니 사람 불러야 된다네요. 아놔... ㅠㅠ",
    },
  {
      id: 6,
      boardType: "free",
      category: "자유",
      title: "AI 시대 최고의 수혜자는 누구일까요?",
      writer: "익명",
      date: "07.05.",
      views: 35,
      isNew: false,
      reactions: {
        like: 1,
        laugh: 0,
        agree: 2,
        thanks: 0,
        wow: 0,
      },
      content: "수업 시간에 이야기했던 AI 시대 직무 변화에 대해 투표를 만들어봤습니다.",
      poll: {
        title: "AI 시대 최고 수혜자는?",
        type: "single",
        deadline: "24시간",
        voters: 12,
        isVoted: true,
        isClosed: true,
        selectedOptionIds: [
          "option-1",
        ],
        options: [
          {
            id: "option-1",
            text: "개발자",
            count: 5,
          },
          {
            id: "option-2",
            text: "PM",
            count: 2,
          },
          {
            id: "option-3",
            text: "웹디자이너",
            count: 3,
          },
          {
            id: "option-4",
            text: "마케터",
            count: 2,
          },
        ],
      },
    },
  {
      id: 7,
      boardType: "free",
      category: "자유",
      title: "이 곳에서 매너 쌓기",
      writer: "미어캣",
      date: "07.04.",
      views: 20,
      isNew: false,
      reactions: {
        like: 0,
        laugh: 0,
        agree: 1,
        thanks: 1,
        wow: 0,
      },
      content: "좋은 계획 뭐 없을까요?\n\n좋아요 댓글?",
    },
  {
      id: 8,
      boardType: "free",
      category: "자유",
      title: "claude fable 5 는 진짜 남다르네요.",
      writer: "솔그루",
      date: "07.05.",
      views: 19,
      isNew: false,
      reactions: {
        like: 0,
        laugh: 1,
        agree: 0,
        thanks: 0,
        wow: 0,
      },
      content: "주간한도 거의 다 써가는데, 몇가지 만들던거 마무리에 사용했습니다.\n그냥 마무리 정도만 할려고 썼는데, 그 결과가 너무 좋네요.\n결국 기존 코드도 fable5 에게 다시 리뷰하고 재작성 시켰습니다.(기능 자체가 달라짐. 대단)",
    },
  {
      id: 9,
      boardType: "free",
      category: "자유",
      title: "나도 홍명보일까? - 상사들",
      writer: "해피아이",
      date: "07.04.",
      views: 22,
      isNew: false,
      reactions: {
        like: 3,
        laugh: 0,
        agree: 1,
        thanks: 1,
        wow: 0,
      },
      content: "홍명보가 절대적으로 비난받고 있고..\n전 국민의 염원을 물거품으로 만든\n장본인으로 우뚝(?) 섰습니다.\n\n그런데...\n딱! 이런 리더십을 가진 사람들이 직장에 존재 한다네요.\n오늘 뉴스 검색하다보니,\n\"우리 상사가 딱 홍명보야\" 하는 반응이 \n직장인들한테 폭풍 공감을 불러오고 있다고 합니다.\n\n혹시..\n홍명보를 비난하고 있지만,\n나도...홍명보 류~~가 아닐까..\n\n직장 상사님들은 한번 쯤 고민해 보시기 바랍니다.",
    },
  {
      id: 10,
      boardType: "free",
      category: "자유",
      title: "자원봉사를 하며 느낀점",
      writer: "Gothrock",
      date: "07.04.",
      views: 21,
      isNew: false,
      reactions: {
        like: 0,
        laugh: 0,
        agree: 0,
        thanks: 0,
        wow: 2,
      },
      content: "제가 하는 자원 봉사는 사실 제 심신의 안정과 평화를 위해 하는 일이라 자기봉사(?)에 가까운 일인데 이걸 주에 두시간씩 하다 보면 노인분들을 정말 많이 대하게 됩니다.\n\n노인 분들과 대화도 하고 웃고 떠들다 문득 문득 드는 생각이 \"아...우리나라 노인분들은 정말 화가 많구나!\"라는 생각인데 사실 화가 많을 수 밖에 없죠??\n\n아침에 일어나서 잠들기 직전까지 뉴스 뉴스 뉴스...끝없이 뉴스만을 보니 화가~! ㅎㅎㅎ\n\n어제 자기봉사 중 드는 생각을 적어보았습니다. 일단 뉴스 끄시고 심신에 평화가 오는 라이프 즐기시기를 기도합니다.",
    },
  {
      id: 11,
      boardType: "free",
      category: "자유",
      title: "다크모드가 눈에 좋은가요?",
      writer: "현상욱",
      date: "07.05.",
      views: 18,
      isNew: false,
      reactions: {
        like: 1,
        laugh: 0,
        agree: 0,
        thanks: 0,
        wow: 0,
      },
      content: "다크모드로 보면 눈에 좋은가요?",
    },
  {
      id: 12,
      boardType: "free",
      category: "자유",
      title: "파이썬이 가장 쉬웠어요",
      writer: "홍길동",
      date: "07.04.",
      views: 16,
      isNew: false,
      reactions: {
        like: 0,
        laugh: 1,
        agree: 0,
        thanks: 0,
        wow: 0,
      },
      content: "파이썬이 가장 쉬웠어요",
    },
]
