const today = new Date().toLocaleDateString('ko-KR', {
  month: '2-digit',
  day: '2-digit',
})

export const resourcePosts = [
  {
    id: 101,
    boardType: 'resource',
    category: '자료',
    title: 'Todo Desktop App 예제 공유합니다',
    writer: '앱메이커',
    date: today,
    views: 41,
    isNew: false,
    reactions: { like: 1, laugh: 0, agree: 0, thanks: 1, wow: 0 },
    content: 'Desktop App 화면을 React로 구성해본 예제 자료입니다.',
  },
  {
    id: 102,
    boardType: 'resource',
    category: '자료',
    title: '날씨 알림 Desktop UI 자료',
    writer: '알림인',
    date: today,
    views: 36,
    isNew: false,
    reactions: { like: 0, laugh: 0, agree: 1, thanks: 0, wow: 0 },
    content: '날씨 정보를 보여주는 Desktop App UI 예제입니다.',
  },
  {
    id: 103,
    boardType: 'resource',
    category: '자료',
    title: '메모앱 컴포넌트 구조 정리',
    writer: '노트왕',
    date: today,
    views: 29,
    isNew: false,
    reactions: { like: 0, laugh: 0, agree: 0, thanks: 0, wow: 0 },
    content: '메모앱을 컴포넌트 단위로 나누는 방법을 정리했습니다.',
  },
  {
    id: 104,
    boardType: 'resource',
    category: '자료',
    title: '음악 플레이어 앱 디자인',
    writer: '뮤직코더',
    date: today,
    views: 55,
    isNew: false,
    reactions: { like: 2, laugh: 0, agree: 0, thanks: 0, wow: 1 },
    content: '음악 플레이어 Desktop App 디자인 시안입니다.',
  },
]
